services:
  - type: web
    name: aqi-predictor-api
    env: python
    plan: free
    buildCommand: pip install -r requirements-api.txt
    startCommand: gunicorn --workers=2 --threads=4 --timeout=120 --bind=0.0.0.0:$PORT app.api:app
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11
      - key: HOPSWORKS_HOST
        value: eu-west.cloud.hopsworks.ai
      - key: CITY
        sync: false
      - key: LAT
        sync: false
      - key: LON
        sync: false
      - key: OPENWEATHER_API_KEY
        sync: false
      - key: HOPSWORKS_API_KEY
        sync: false
      - key: HOPSWORKS_PROJECT
        sync: false
